apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-application.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: {{ include "my-application.name" . }}-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-application.fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
  selector:
    app: {{ include "my-application.name" . }}-backend
